/*
 * Automatically generated C config: don't edit
 */
#define AUTOCONF_INCLUDED

/*
 * Code maturity level options
 */
#define CONFIG_EXPERIMENTAL 1

/*
 * Machine selection
 */
#undef  CONFIG_ACER_PICA_61
#undef  CONFIG_ALGOR_P4032
#undef  CONFIG_DECSTATION
#undef  CONFIG_DESKSTATION_RPC44
#undef  CONFIG_DESKSTATION_TYNE
#undef  CONFIG_MIPS_MAGNUM_3000
#define CONFIG_COBALT_MICRO_SERVER 1
#undef  CONFIG_MIPS_MAGNUM_4000
#undef  CONFIG_OLIVETTI_M700
#undef  CONFIG_SGI
#undef  CONFIG_SNI_RM200_PCI
#define COBALT_MICRO_SERVER 1
#define CONFIG_NO_SWAPPER 1
#define CONFIG_COBALT_27 1
#define CONFIG_NO_KEYBOARD 1
#define CONFIG_NO_VIDEO_CONSOLE 1
#define CONFIG_COBALT_LCD 1
#define CONFIG_COBALT_SERIAL 1
#define CONFIG_PCI 1
#define CONFIG_COBALT_28 1

/*
 * CPU selection
 */
#undef  CONFIG_CPU_R3000
#undef  CONFIG_CPU_R6000
#undef  CONFIG_CPU_R4300
#undef  CONFIG_CPU_R4X00
#undef  CONFIG_CPU_R5000
#define CONFIG_CPU_NEVADA 1
#undef  CONFIG_CPU_R8000
#undef  CONFIG_CPU_R10000

/*
 * General setup
 */
#define CONFIG_ELF_KERNEL 1
#define CONFIG_CPU_LITTLE_ENDIAN 1
#undef  CONFIG_BINFMT_AOUT
#define CONFIG_BINFMT_ELF 1
#undef  CONFIG_BINFMT_MISC
#define CONFIG_BINFMT_MISC_MODULE 1
#undef  CONFIG_BINFMT_JAVA
#define CONFIG_NET 1
#define CONFIG_SYSVIPC 1
#define CONFIG_SYSCTL 1
#undef  CONFIG_PARPORT

/*
 * Loadable module support
 */
#define CONFIG_MODULES 1
#define CONFIG_MODVERSIONS 1
#define CONFIG_KERNELD 1

/*
 * Floppy, IDE, and other block devices
 */
#undef  CONFIG_BLK_DEV_FD
#define CONFIG_BLK_DEV_IDE 1

/*
 * Please see Documentation/ide.txt for help/info on IDE drives
 */
#undef  CONFIG_BLK_DEV_HD_IDE
#undef  CONFIG_BLK_DEV_IDECD
#undef  CONFIG_BLK_DEV_IDETAPE
#undef  CONFIG_BLK_DEV_IDEFLOPPY
#undef  CONFIG_BLK_DEV_IDESCSI
#undef  CONFIG_BLK_DEV_IDE_PCMCIA
#undef  CONFIG_BLK_DEV_CMD640
#undef  CONFIG_BLK_DEV_RZ1000
#undef  CONFIG_BLK_DEV_TRITON
#define CONFIG_BLK_DEV_COBALT 1
#define CONFIG_BLK_DEV_COBALT_SECONDARY 1
#undef  CONFIG_IDE_CHIPSETS

/*
 * Additional Block Devices
 */
#undef  CONFIG_BLK_DEV_LOOP
#define CONFIG_BLK_DEV_LOOP_MODULE 1
#define CONFIG_BLK_DEV_MD 1
#define CONFIG_MD_LINEAR 1
#define CONFIG_MD_STRIPED 1
#define CONFIG_MD_MIRRORING 1
#define CONFIG_MD_RAID5 1
#undef  CONFIG_BLK_DEV_RAM
#define CONFIG_BLK_DEV_RAM_MODULE 1
#undef  CONFIG_BLK_DEV_XD
#undef  CONFIG_BLK_DEV_HD

/*
 * Networking options
 */
#define CONFIG_FIREWALL 1
#define CONFIG_NET_ALIAS 1
#define CONFIG_INET 1
#define CONFIG_IP_FORWARD 1
#define CONFIG_IP_MULTICAST 1
#define CONFIG_SYN_COOKIES 1
#define CONFIG_IP_FIREWALL 1
#define CONFIG_IP_FIREWALL_VERBOSE 1
#define CONFIG_IP_MASQUERADE 1

/*
 * Protocol-specific masquerading support will be built as modules.
 */
#define CONFIG_IP_MASQUERADE_IPAUTOFW 1
#define CONFIG_IP_MASQUERADE_IPPORTFW 1
#define CONFIG_IP_MASQUERADE_ICMP 1
#define CONFIG_IP_TRANSPARENT_PROXY 1
#define CONFIG_IP_ALWAYS_DEFRAG 1
#define CONFIG_IP_ACCT 1
#undef  CONFIG_IP_ROUTER
#undef  CONFIG_NET_IPIP
#define CONFIG_IP_MROUTE 1
#undef  CONFIG_IP_ALIAS
#define CONFIG_IP_ALIAS_MODULE 1

/*
 * (it is safe to leave these untouched)
 */
#undef  CONFIG_INET_PCTCP
#undef  CONFIG_INET_RARP
#undef  CONFIG_NO_PATH_MTU_DISCOVERY
#define CONFIG_IP_NOSR 1
#define CONFIG_SKB_LARGE 1

/*
 *  
 */
#undef  CONFIG_IPX
#define CONFIG_IPX_MODULE 1
#undef  CONFIG_ATALK
#define CONFIG_ATALK_MODULE 1
#undef  CONFIG_AX25
#undef  CONFIG_BRIDGE
#undef  CONFIG_NETLINK

/*
 * SCSI support
 */
#define CONFIG_SCSI 1

/*
 * SCSI support type (disk, tape, CD-ROM)
 */
#define CONFIG_BLK_DEV_SD 1
#undef  CONFIG_CHR_DEV_ST
#define CONFIG_CHR_DEV_ST_MODULE 1
#undef  CONFIG_BLK_DEV_SR
#define CONFIG_BLK_DEV_SR_MODULE 1
#undef  CONFIG_CHR_DEV_SG
#define CONFIG_CHR_DEV_SG_MODULE 1

/*
 * Some SCSI devices (e.g. CD jukebox) support multiple LUNs
 */
#define CONFIG_SCSI_MULTI_LUN 1
#define CONFIG_SCSI_CONSTANTS 1

/*
 * SCSI low-level drivers
 */
#undef  CONFIG_SCSI_7000FASST
#undef  CONFIG_SCSI_AHA152X
#undef  CONFIG_SCSI_AHA1542
#undef  CONFIG_SCSI_AHA1740
#define CONFIG_SCSI_AIC7XXX 1
#undef  CONFIG_OVERRIDE_CMDS
#undef  CONFIG_AIC7XXX_PROC_STATS
#define CONFIG_AIC7XXX_RESET_DELAY (5)
#undef  CONFIG_SCSI_ADVANSYS
#undef  CONFIG_SCSI_IN2000
#undef  CONFIG_SCSI_AM53C974
#undef  CONFIG_SCSI_BUSLOGIC
#undef  CONFIG_SCSI_DTC3280
#undef  CONFIG_SCSI_EATA_DMA
#undef  CONFIG_SCSI_EATA_PIO
#undef  CONFIG_SCSI_EATA
#undef  CONFIG_SCSI_FUTURE_DOMAIN
#undef  CONFIG_SCSI_GENERIC_NCR5380
#undef  CONFIG_SCSI_NCR53C406A
#undef  CONFIG_SCSI_NCR53C7xx
#define CONFIG_SCSI_NCR53C8XX 1
#undef  CONFIG_SCSI_NCR53C8XX_NVRAM_DETECT
#define CONFIG_SCSI_NCR53C8XX_TAGGED_QUEUE 1
#define CONFIG_SCSI_NCR53C8XX_IOMAPPED 1
#define CONFIG_SCSI_NCR53C8XX_MAX_TAGS (4)
#define CONFIG_SCSI_NCR53C8XX_SYNC (5)
#undef  CONFIG_SCSI_NCR53C8XX_SYMBIOS_COMPAT
#undef  CONFIG_SCSI_PPA
#undef  CONFIG_SCSI_PAS16
#undef  CONFIG_SCSI_QLOGIC_FAS
#undef  CONFIG_SCSI_QLOGIC_ISP
#undef  CONFIG_SCSI_SEAGATE
#undef  CONFIG_SCSI_DC390T
#undef  CONFIG_SCSI_T128
#undef  CONFIG_SCSI_U14_34F
#undef  CONFIG_SCSI_ULTRASTOR
#undef  CONFIG_SCSI_GDTH

/*
 * Network device support
 */
#define CONFIG_NETDEVICES 1
#undef  CONFIG_DUMMY
#define CONFIG_DUMMY_MODULE 1
#undef  CONFIG_EQUALIZER
#undef  CONFIG_DLCI
#define CONFIG_DLCI_MODULE 1
#define CONFIG_DLCI_COUNT (24)
#define CONFIG_DLCI_MAX (8)
#undef  CONFIG_SDLA
#define CONFIG_DLCI_MODULE 1
#undef  CONFIG_PLIP
#undef  CONFIG_PPP
#define CONFIG_PPP_MODULE 1

/*
 * CCP compressors for PPP are only built as modules.
 */
#undef  CONFIG_SLIP
#define CONFIG_SLIP_MODULE 1
#define CONFIG_SLIP_COMPRESSED 1
#define CONFIG_SLIP_SMART 1
#undef  CONFIG_SLIP_MODE_SLIP6
#undef  CONFIG_NET_RADIO
#define CONFIG_NET_ETHERNET 1
#undef  CONFIG_NET_VENDOR_3COM
#undef  CONFIG_NET_VENDOR_SMC
#undef  CONFIG_NET_PCI
#undef  CONFIG_NET_ISA
#define CONFIG_NET_EISA 1
#undef  CONFIG_AC3200
#undef  CONFIG_APRICOT
#define CONFIG_COBALT_TULIP 1
#undef  CONFIG_COBALT_3COM
#define CONFIG_COBALT_3COM_MODULE 1
#undef  CONFIG_COBALT_E100
#define CONFIG_COBALT_E100_MODULE 1
#undef  CONFIG_ZNET
#undef  CONFIG_NET_POCKET
#undef  CONFIG_TR
#undef  CONFIG_FDDI
#undef  CONFIG_ARCNET

/*
 * ISDN subsystem
 */
#undef  CONFIG_ISDN
#define CONFIG_ISDN_MODULE 1
#define CONFIG_ISDN_PPP 1
#define CONFIG_ISDN_PPP_VJ 1
#define CONFIG_ISDN_MPP 1
#define CONFIG_ISDN_AUDIO 1
#undef  CONFIG_ISDN_DRV_ICN
#undef  CONFIG_ISDN_DRV_LOOP
#undef  CONFIG_ISDN_DRV_PCBIT
#undef  CONFIG_ISDN_DRV_HISAX
#define CONFIG_ISDN_DRV_HISAX_MODULE 1
#define CONFIG_HISAX_EURO 1
#define CONFIG_DE_AOC 1
#undef  CONFIG_HISAX_NO_SENDCOMPLETE
#undef  CONFIG_HISAX_NO_LLC
#define CONFIG_HISAX_1TR6 1
#undef  CONFIG_HISAX_16_0
#undef  CONFIG_HISAX_16_3
#undef  CONFIG_HISAX_TELES3C
#undef  CONFIG_HISAX_TELESPCI
#undef  CONFIG_HISAX_S0BOX
#undef  CONFIG_HISAX_AVM_A1
#undef  CONFIG_HISAX_FRITZPCI
#undef  CONFIG_HISAX_AVM_A1_PCMCIA
#define CONFIG_HISAX_ELSA 1
#undef  CONFIG_HISAX_IX1MICROR2
#undef  CONFIG_HISAX_DIEHLDIVA
#undef  CONFIG_HISAX_ASUSCOM
#undef  CONFIG_HISAX_TELEINT
#undef  CONFIG_HISAX_SEDLBAUER
#undef  CONFIG_HISAX_SPORTSTER
#undef  CONFIG_HISAX_MIC
#undef  CONFIG_HISAX_NETJET
#undef  CONFIG_HISAX_NICCY
#undef  CONFIG_ISDN_DRV_SC
#undef  CONFIG_ISDN_DRV_AVMB1
#define CONFIG_ISDN_DRV_AVMB1_MODULE 1
#define CONFIG_ISDN_DRV_AVMB1_VERBOSE_REASON 1

/*
 * CD-ROM drivers (not for SCSI or IDE/ATAPI drives)
 */
#undef  CONFIG_CD_NO_IDESCSI

/*
 * Filesystems
 */
#define CONFIG_QUOTA 1
#undef  CONFIG_MINIX_FS
#undef  CONFIG_EXT_FS
#define CONFIG_EXT2_FS 1
#undef  CONFIG_XIA_FS
#undef  CONFIG_NLS
#define CONFIG_NLS_MODULE 1
#undef  CONFIG_ISO9660_FS
#define CONFIG_ISO9660_FS_MODULE 1
#undef  CONFIG_FAT_FS
#define CONFIG_FAT_FS_MODULE 1
#undef  CONFIG_MSDOS_FS
#define CONFIG_MSDOS_FS_MODULE 1
#undef  CONFIG_UMSDOS_FS
#undef  CONFIG_VFAT_FS
#define CONFIG_VFAT_FS_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_437
#define CONFIG_NLS_CODEPAGE_437_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_737
#define CONFIG_NLS_CODEPAGE_737_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_775
#define CONFIG_NLS_CODEPAGE_775_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_850
#define CONFIG_NLS_CODEPAGE_850_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_852
#define CONFIG_NLS_CODEPAGE_852_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_855
#define CONFIG_NLS_CODEPAGE_855_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_857
#define CONFIG_NLS_CODEPAGE_857_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_860
#define CONFIG_NLS_CODEPAGE_860_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_861
#define CONFIG_NLS_CODEPAGE_861_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_862
#define CONFIG_NLS_CODEPAGE_862_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_863
#define CONFIG_NLS_CODEPAGE_863_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_864
#define CONFIG_NLS_CODEPAGE_864_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_865
#define CONFIG_NLS_CODEPAGE_865_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_866
#define CONFIG_NLS_CODEPAGE_866_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_869
#define CONFIG_NLS_CODEPAGE_869_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_874
#define CONFIG_NLS_CODEPAGE_874_MODULE 1
#undef  CONFIG_NLS_ISO8859_1
#define CONFIG_NLS_ISO8859_1_MODULE 1
#undef  CONFIG_NLS_ISO8859_2
#define CONFIG_NLS_ISO8859_2_MODULE 1
#undef  CONFIG_NLS_ISO8859_3
#define CONFIG_NLS_ISO8859_3_MODULE 1
#undef  CONFIG_NLS_ISO8859_4
#define CONFIG_NLS_ISO8859_4_MODULE 1
#undef  CONFIG_NLS_ISO8859_5
#define CONFIG_NLS_ISO8859_5_MODULE 1
#undef  CONFIG_NLS_ISO8859_6
#define CONFIG_NLS_ISO8859_6_MODULE 1
#undef  CONFIG_NLS_ISO8859_7
#define CONFIG_NLS_ISO8859_7_MODULE 1
#undef  CONFIG_NLS_ISO8859_8
#define CONFIG_NLS_ISO8859_8_MODULE 1
#undef  CONFIG_NLS_ISO8859_9
#define CONFIG_NLS_ISO8859_9_MODULE 1
#undef  CONFIG_NLS_KOI8_R
#define CONFIG_NLS_KOI8_R_MODULE 1
#define CONFIG_PROC_FS 1
#define CONFIG_NFS_FS 1
#define CONFIG_ROOT_NFS 1
#define CONFIG_RNFS_BOOTP 1
#undef  CONFIG_RNFS_RARP
#undef  CONFIG_SMB_FS
#define CONFIG_SMB_FS_MODULE 1
#define CONFIG_SMB_WIN95 1
#undef  CONFIG_NCP_FS
#undef  CONFIG_HPFS_FS
#undef  CONFIG_SYSV_FS
#undef  CONFIG_AUTOFS_FS
#undef  CONFIG_AFFS_FS
#undef  CONFIG_UFS_FS

/*
 * Character devices
 */
#undef  CONFIG_SERIAL
#undef  CONFIG_PCI_SERIAL
#define CONFIG_PCI_SERIAL_MODULE 1
#undef  CONFIG_DIGI
#undef  CONFIG_CYCLADES
#undef  CONFIG_STALDRV
#undef  CONFIG_RISCOM8
#undef  CONFIG_PRINTER
#undef  CONFIG_SPECIALIX
#undef  CONFIG_MOUSE
#undef  CONFIG_UMISC
#undef  CONFIG_QIC02_TAPE
#undef  CONFIG_FTAPE
#undef  CONFIG_APM
#undef  CONFIG_WATCHDOG
#define CONFIG_RTC 1

/*
 * Sound
 */
#undef  CONFIG_SOUND

/*
 * Kernel hacking
 */
#undef  CONFIG_CROSSCOMPILE
#undef  CONFIG_REMOTE_DEBUG
#undef  CONFIG_PROFILE
